### ISSUE TITLE
Delete a specific location within a day

### ISSUE THREAD

**Issue by gsu421** [joeyps/jourmap#143]
Cannot delete the location within a journey.

**Comment by joeyps** [comment]
I change the UI layout, we won't show places after day any more

**Comment by gsu421** [comment]
Not sure if it's a bug or that I am not familiar with the layout.
![2015-02-25_1-21-47](https://cloud.githubusercontent.com/assets/10541291/6366558/0fb88136-bc8d-11e4-854e-cbc61534e63f.jpg)

**Comment by joeyps** [comment]
The simplest way is to set another place for these photos, then refresh the page

**Comment by gsu421** [comment]
Refresh helps after deleting all the photos.
